-- =============================================================================
-- AlgoTrader Pro - Database Schema
-- SQLite-compatible SQL
-- =============================================================================

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;
PRAGMA synchronous = NORMAL;

-- =============================================================================
-- OHLCV Data
-- Stores candlestick data fetched from CoinGecko (Phase 1) / Bybit (Phase 2)
-- =============================================================================
CREATE TABLE IF NOT EXISTS ohlcv (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol        TEXT    NOT NULL,                     -- e.g. BTCUSDT
    timeframe     TEXT    NOT NULL,                     -- e.g. 1h, 4h, 1d
    open_time     INTEGER NOT NULL,                     -- Unix timestamp ms (candle open)
    open          REAL    NOT NULL,
    high          REAL    NOT NULL,
    low           REAL    NOT NULL,
    close         REAL    NOT NULL,
    volume        REAL    NOT NULL,
    close_time    INTEGER,                              -- Unix timestamp ms (candle close)
    created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),

    CONSTRAINT uq_ohlcv_symbol_tf_time UNIQUE (symbol, timeframe, open_time)
);

CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_tf          ON ohlcv (symbol, timeframe);
CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_tf_time     ON ohlcv (symbol, timeframe, open_time DESC);
CREATE INDEX IF NOT EXISTS idx_ohlcv_open_time          ON ohlcv (open_time DESC);

-- =============================================================================
-- Trades
-- Records every paper/live trade from entry to exit
-- =============================================================================
CREATE TABLE IF NOT EXISTS trades (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    trade_id            TEXT    NOT NULL UNIQUE,            -- UUID generated by system
    symbol              TEXT    NOT NULL,                   -- e.g. BTCUSDT
    direction           TEXT    NOT NULL CHECK (direction IN ('long', 'short')),
    status              TEXT    NOT NULL DEFAULT 'open'
                                CHECK (status IN ('open', 'closed', 'cancelled', 'error')),

    -- Entry
    entry_time          TEXT    NOT NULL,                   -- ISO-8601 UTC
    entry_price         REAL    NOT NULL,
    entry_slippage      REAL    NOT NULL DEFAULT 0.0,       -- Actual slippage at entry (%)
    entry_fee           REAL    NOT NULL DEFAULT 0.0,       -- Fee paid at entry (USDT)
    quantity            REAL    NOT NULL,                   -- Base asset quantity
    notional_value      REAL    NOT NULL,                   -- Entry price * quantity (USDT)

    -- Sizing
    kelly_fraction      REAL,                               -- Kelly fraction used for sizing
    risk_amount         REAL,                               -- USDT at risk (distance to stop * qty)

    -- Exit
    exit_time           TEXT,                               -- ISO-8601 UTC (NULL if open)
    exit_price          REAL,
    exit_slippage       REAL    DEFAULT 0.0,
    exit_fee            REAL    DEFAULT 0.0,
    exit_reason         TEXT    CHECK (exit_reason IN (
                            'stop_loss', 'take_profit', 'trailing_stop',
                            'time_exit', 'signal_reversal', 'manual',
                            'drawdown_pause', 'error', NULL
                        )),

    -- P&L
    gross_pnl           REAL,                               -- Before fees (USDT)
    net_pnl             REAL,                               -- After fees (USDT)
    pnl_pct             REAL,                               -- Net P&L as % of notional
    duration_minutes    INTEGER,                            -- Trade duration in minutes

    -- Risk levels at entry
    stop_loss_price     REAL    NOT NULL,
    take_profit_price   REAL,
    atr_at_entry        REAL,                               -- ATR value when trade opened

    -- Signal metadata
    confidence_score    REAL    NOT NULL,                   -- 0-100 composite score
    signal_breakdown    TEXT,                               -- JSON: per-layer scores
    leverage            REAL    DEFAULT 1.0,                 -- Leverage used (1x=spot, 2-10x simulated)

    -- Audit
    created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_trades_symbol          ON trades (symbol);
CREATE INDEX IF NOT EXISTS idx_trades_status          ON trades (status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time      ON trades (entry_time DESC);
CREATE INDEX IF NOT EXISTS idx_trades_direction       ON trades (direction);
CREATE INDEX IF NOT EXISTS idx_trades_exit_reason     ON trades (exit_reason);

-- Trigger to auto-update updated_at on trade modification
CREATE TRIGGER IF NOT EXISTS trg_trades_updated_at
    AFTER UPDATE ON trades
    FOR EACH ROW
BEGIN
    UPDATE trades SET updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
    WHERE id = OLD.id;
END;

-- =============================================================================
-- Equity Snapshots
-- Periodic snapshots of portfolio value for equity curve tracking
-- =============================================================================
CREATE TABLE IF NOT EXISTS equity_snapshots (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp       TEXT    NOT NULL UNIQUE,                -- ISO-8601 UTC
    equity          REAL    NOT NULL,                       -- Total portfolio value (USDT)
    cash            REAL    NOT NULL,                       -- Available cash (USDT)
    positions_value REAL    NOT NULL DEFAULT 0.0,           -- Mark-to-market value of open positions
    drawdown_pct    REAL    NOT NULL DEFAULT 0.0,           -- Current drawdown from equity peak (%)
    open_trades     INTEGER NOT NULL DEFAULT 0             -- Number of open positions
);

CREATE INDEX IF NOT EXISTS idx_equity_snapshots_ts ON equity_snapshots (timestamp DESC);

-- =============================================================================
-- Signals Log
-- Records every signal generated (whether acted on or not)
-- =============================================================================
CREATE TABLE IF NOT EXISTS signals_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp       TEXT    NOT NULL,                       -- ISO-8601 UTC when signal generated
    symbol          TEXT    NOT NULL,
    timeframe       TEXT    NOT NULL,
    confidence_score REAL   NOT NULL,                       -- 0-100 composite score
    direction       TEXT    NOT NULL CHECK (direction IN ('long', 'short', 'neutral')),

    -- Layer scores (0-100 each)
    layer1_score    REAL    NOT NULL DEFAULT 0.0,           -- Technical
    layer2_score    REAL    NOT NULL DEFAULT 0.0,           -- Volume
    layer3_score    REAL    NOT NULL DEFAULT 0.0,           -- Sentiment
    ml_score        REAL    NOT NULL DEFAULT 0.0,           -- ML ensemble

    -- Raw signal details
    raw_signals     TEXT,                                   -- JSON: individual indicator values

    -- What happened
    action_taken    TEXT    NOT NULL CHECK (action_taken IN (
                        'trade_opened', 'skipped_threshold', 'skipped_max_positions',
                        'skipped_cooldown', 'skipped_correlation', 'skipped_ev_negative',
                        'skipped_drawdown_pause', 'skipped_short_disabled', 'error'
                    )),
    trade_id        TEXT    REFERENCES trades (trade_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_signals_ts       ON signals_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_symbol   ON signals_log (symbol);
CREATE INDEX IF NOT EXISTS idx_signals_action   ON signals_log (action_taken);
CREATE INDEX IF NOT EXISTS idx_signals_trade_id ON signals_log (trade_id);

-- =============================================================================
-- Sentiment Data
-- News sentiment, Fear & Greed index, and other sentiment sources
-- =============================================================================
CREATE TABLE IF NOT EXISTS sentiment_data (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp   TEXT    NOT NULL,                           -- ISO-8601 UTC
    source      TEXT    NOT NULL,                           -- cryptopanic | fear_greed | google_trends
    symbol      TEXT,                                       -- NULL = market-wide (e.g. F&G index)
    value       REAL    NOT NULL,                           -- Normalized score [-1.0 to 1.0] or [0-100]
    raw_data    TEXT,                                       -- JSON: full API response snapshot

    CONSTRAINT uq_sentiment_ts_source_symbol UNIQUE (timestamp, source, symbol)
);

CREATE INDEX IF NOT EXISTS idx_sentiment_ts         ON sentiment_data (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_sentiment_source     ON sentiment_data (source);
CREATE INDEX IF NOT EXISTS idx_sentiment_symbol     ON sentiment_data (symbol);
CREATE INDEX IF NOT EXISTS idx_sentiment_src_sym    ON sentiment_data (source, symbol, timestamp DESC);

-- =============================================================================
-- ML Model Runs
-- Tracks model training runs, hyperparameters, and evaluation metrics
-- =============================================================================
CREATE TABLE IF NOT EXISTS ml_model_runs (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id              TEXT    NOT NULL UNIQUE,            -- UUID
    model_type          TEXT    NOT NULL CHECK (model_type IN ('xgboost', 'random_forest', 'lstm', 'ensemble')),
    symbol              TEXT    NOT NULL,
    timeframe           TEXT    NOT NULL,

    -- Training data range
    train_start         TEXT    NOT NULL,                   -- ISO-8601 date
    train_end           TEXT    NOT NULL,                   -- ISO-8601 date

    -- Evaluation metrics (on held-out test set)
    accuracy            REAL,                               -- Overall accuracy
    precision_pos       REAL,                               -- Precision for positive class
    recall_pos          REAL,                               -- Recall for positive class
    f1_score            REAL,                               -- F1 score for positive class
    roc_auc             REAL,                               -- ROC-AUC score

    -- Training details
    n_train_samples     INTEGER,
    n_test_samples      INTEGER,
    training_duration_s REAL,                               -- Wall-clock training time (seconds)

    -- Serialized metadata
    hyperparams         TEXT    NOT NULL,                   -- JSON: model hyperparameters used
    feature_importance  TEXT,                               -- JSON: feature name -> importance score

    -- Model artifact path
    model_path          TEXT,                               -- Path to saved .pkl / .pt file

    trained_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_ml_runs_symbol       ON ml_model_runs (symbol, timeframe);
CREATE INDEX IF NOT EXISTS idx_ml_runs_model_type   ON ml_model_runs (model_type);
CREATE INDEX IF NOT EXISTS idx_ml_runs_trained_at   ON ml_model_runs (trained_at DESC);

-- =============================================================================
-- Backtest Results
-- Stores results from backtesting runs including Monte Carlo data
-- =============================================================================
CREATE TABLE IF NOT EXISTS backtest_results (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id              TEXT    NOT NULL UNIQUE,            -- UUID
    config_snapshot     TEXT    NOT NULL,                   -- JSON: full config at time of run

    -- Date range
    start_date          TEXT    NOT NULL,                   -- ISO-8601 date
    end_date            TEXT    NOT NULL,                   -- ISO-8601 date

    -- Capital
    initial_capital     REAL    NOT NULL,
    final_equity        REAL    NOT NULL,

    -- Performance metrics
    total_return_pct    REAL    NOT NULL,
    sharpe_ratio        REAL,
    sortino_ratio       REAL,
    max_drawdown_pct    REAL    NOT NULL,
    calmar_ratio        REAL,
    profit_factor       REAL,

    -- Trade statistics
    win_rate            REAL,                               -- Win rate 0.0 to 1.0
    total_trades        INTEGER NOT NULL DEFAULT 0,
    winning_trades      INTEGER NOT NULL DEFAULT 0,
    losing_trades       INTEGER NOT NULL DEFAULT 0,
    avg_win_pct         REAL,
    avg_loss_pct        REAL,
    avg_hold_hours      REAL,

    -- Monte Carlo results
    monte_carlo_data    TEXT,                               -- JSON: simulation results

    -- Symbol(s) tested
    symbols             TEXT,                               -- JSON array of symbols

    created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_backtest_created_at  ON backtest_results (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_return      ON backtest_results (total_return_pct DESC);

-- =============================================================================
-- Bot Events
-- System-level events: startup, shutdown, errors, pauses, etc.
-- =============================================================================
CREATE TABLE IF NOT EXISTS bot_events (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    event_type  TEXT    NOT NULL CHECK (event_type IN (
                    'startup', 'shutdown', 'pause', 'resume',
                    'error', 'warning', 'info',
                    'drawdown_pause', 'ev_pause', 'daily_loss_pause',
                    'retrain_start', 'retrain_complete',
                    'trade_opened', 'trade_closed', 'position_rejected'
                )),
    reason      TEXT,                                       -- Human-readable reason
    details     TEXT,                                       -- JSON: additional structured data
    timestamp   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_bot_events_type  ON bot_events (event_type);
CREATE INDEX IF NOT EXISTS idx_bot_events_ts    ON bot_events (timestamp DESC);

-- =============================================================================
-- Schema Version (for migrations)
-- =============================================================================
CREATE TABLE IF NOT EXISTS schema_version (
    version     INTEGER NOT NULL,
    applied_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    description TEXT
);

INSERT OR IGNORE INTO schema_version (version, description)
VALUES (1, 'Initial schema - Phase 1 Paper Trading');
